### ISSUE TITLE
Fix issue of rosserial_arduino losing sync with device

### ISSUE THREAD

**Issue by 7ayushgupta** [AUV-IITK/Anahita#32]
We have changed to a single message for Thrusters, but we have not tested it yet. We need to find a way to launch the node again if it loses sync.
Currently, we manually launch the code again when it fails, and the thrusters lose on control till then.

I was thinking of implementing something like a Bash script which is capable of this because even if we find something that lowers this occurrence, I dont want to risk it.

**Comment by 7ayushgupta** [comment]
I read that. But `respawn=true` will only relaunch the node if the node stops entirely. Which actually is not happening in our case. The node is running but it gives an error, which does not allow us to control the thrusters anymore.

**Comment by ksakash** [comment]
@7ayushgupta close this? As we have already found a solution for this.

**Comment by 7ayushgupta** [comment]
Solved. Closing this.
