### ISSUE TITLE
Using base classes to reduce the redundancy

### ISSUE THREAD

**Issue by ksakash** [AUV-IITK/Anahita#35]
In the packages like `task_handler_layer` & `vision_tasks`, there are a bunch of classes designed to do specific tasks, but the design of every class is more or less like others. So, more often than not we just copy paste code when creating a new class which feels stupid sometimes as to why bothering to write so much code for a class which is very little different from other. I propose to create a single base class which has the basic requirements needed by all the other tasks and the specific tasks are derived from it. This way will give the code base better structure and scalability.

**Comment by 7ayushgupta** [comment]
Yes, I agree with that. Too much of redundancy.

**Comment by 7ayushgupta** [comment]
Completed with @jayeshaw's PR #55
