### ISSUE TITLE
Separate vision_layer

### ISSUE THREAD

**Issue by ksakash** [AUV-IITK/Anahita#6]
Since we are going to develop a separate `vision_layer` , which was before incorporated in the `task_handler_layer`, so we need to decide its organisation. For now, I have made a basic layout of the layer which can be used as a starting point to work on.
```
vision_layer/
├── calibration
├── cfg
├── CMakeLists.txt
├── color_processing
├── feature_detectors
├── filters
├── launch
├── package.xml
└── src
```

**Comment by Mayankm96** [comment]
Shouldn't `color_processing`, `feature_detectors` and `filters` just be libraries? In that case, all of that would come under `include` directory, right?

**Comment by ksakash** [comment]
Yeah...Right, all will be under `include`. Then the layout will be..
```vision_layer/
├── calibration
├── cfg
├── CMakeLists.txt
├── include
│   ├── color_processing
│   ├── feature_detectors
│   └── filters
├── launch
├── package.xml
└── src
```

**Comment by Mayankm96** [comment]
How is each task being dealt with in this case?

**Comment by ksakash** [comment]
`feature_detector` will be responsible for getting all the features from an object like its coordinates, contours, etc. It will contain the target specific code to get the info about the targets like `buoy_detector`, `gate_detector`, etc. The main code will be written inside `src` which will sequentially send the information to the `task_handler_layer` using the `feature_detector` lib.

**Comment by Mayankm96** [comment]
Hm so how about we have a separate package named `vision_commons` which will have all the common libraries that we create and then separate packages for each task? Also, I was thinking of using service-client nodes for tasks instead of normal subscribers-publishers.

**Comment by ksakash** [comment]
Instead of making separate packages, why can't we make special classes for the tasks and include those classes in the main vision code. So, there will be no separate packages for doing the tasks but one main vision code where we can create objects for handling all the detection related work and executing them sequentially according to the motion plan.

**Comment by ksakash** [comment]
Also by making separate packages we will repeat the same thing again. One of the things that I felt wrong with the previous code was a lot of repetition. Even for different tasks containing 300 lines of code there is literally very few lines of difference. By doing the first way we can use the inheritance property of C++ and develop a base obstacle_detector class and derive the other classes from it.

**Comment by ksakash** [comment]
Anyway, I will make a full proof plan of the whole thing that I have in mind, with all the pros and cons and get back to you @Mayankm96 .

**Comment by naishadhparmar** [comment]
In my opinion, this should be the package structure
```
├── calibration
├── cfg
├── CMakeLists.txt
├── include
│   ├── color_processing
│   ├── feature_detectors
│   └── filters
├── launch
├── package.xml
└── src
     ├── buoy_detection.cpp
     ├── gate_detection.cpp
     ├── .
     ├── . more nodes
     ├── .
     └── last_node.cpp
```
This is essentially what @ksakash said.
I don't see the point of making an entirely new package only for the libraries, since we are writing those files in `vision_layer/include` and this library won't be used anywhere else except `vision_layer`. I agree with @Mayankm96 that we can use a client-service system instead of subscriber-publisher because we will need only one type of data (buoy, gate, marker dropper...) at a time and not all types of data at all times. What type of data is needed at a particular moment will be decided by `master_layer`.

**Comment by Mayankm96** [comment]
The only reason why I suggest to have different packages is to avoid having too many nodes inside one package itself.  Moreover, the service messages would be added to the `hyperion_msgs` package since it is a recommended way to organize a ROS repository.

**Comment by ksakash** [comment]
Hmm... We will not need too many nodes or packages. According to the plan there will separate classes for each mission element to handle all the operations to get the necessary information, under `feature_detector`. We can apply `Service` in the classes too, i guess, by initialising a `node_handle` inside the classes. So, we will not need distinct nodes for each task, but just separate objects to handle each tasks, which will be included in a single vision code.

**Comment by Suryansh470** [comment]
@ksakash just wanted to know that is this organisation of vision layer being followed for our new vehicle........?????

**Comment by 7ayushgupta** [comment]
We can close this issue I believe.
