### ISSUE TITLE
Fix the services to reset odometry

### ISSUE THREAD

**Issue by 7ayushgupta** [AUV-IITK/Anahita#60]
https://github.com/AUV-IITK/Anahita/blob/650c4b1c093ffe0093a45a4d60f970c374a9e5df/navigation_layer/odom_dvl_imu/src/nav_main.cpp#L49

@ksakash can you please fix these two services? You just need to make a new branch, and figure out a way how to do this. I am trying to solve this, but it's going wrong each time.

**Comment by ksakash** [comment]
fixed in https://github.com/AUV-IITK/Anahita/commit/8db6217c816b91050517953beaeeae58f541771d
